package com.aliyo.todoapp.config;


import com.aliyo.todoapp.model.Role;
import com.aliyo.todoapp.model.User;
import com.aliyo.todoapp.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.HashSet;
import java.util.Set;

@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    public void run(String... args) {
        // Check if admin user exists
        if (!userRepository.existsByUsername("admin")) {
            User adminUser = new User();
            // ID will be automatically generated by UUID in the User class
            adminUser.setUsername("admin");
            adminUser.setEmail("admin@admin.com");
            adminUser.setPassword(passwordEncoder.encode("admin123"));
            adminUser.setActive(true);

            Set<Role> roles = new HashSet<>();
            roles.add(Role.ROLE_ADMIN);
            roles.add(Role.ROLE_USER);
            adminUser.setRoles(roles);

            userRepository.save(adminUser);

            System.out.println("Admin user created successfully with ID: " + adminUser.getId());
        }
    }
}